### ISSUE TITLE
WS100+/WD100+ devices are not responding and not reporting state

### ISSUE THREAD

**Issue by RandomEngy** [jshessen/SmartThingsEdgeDrivers#26]
All of my WS100+ and WD100+ switches using this device driver have ceased to function. They no longer turn on or off when I control them from the app and they no longer show the current on/off state. No events show up in the logs for the device.

Other devices are still working. This has persisted for 9 hours so far. I've tried power cycling the SmartThings hub but that hasn't helped.

What can I do to diagnose this?

**To Reproduce**
Toggle a light on or off from the SmartThings app

**Expected behavior**
The light changes

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: Android 13

**Comment by jshessen** [comment]
@RandomEngy

I was finally able to definitively track down the root of this issue.  The problem was introduced as I was going through a git rebase of my code between the beta branch and the main branch.  This carried over a typo in the init.lua of the switches driver.  Specifically in the 'requires' section of the code a reference to "st.Device" vs. "st.device"

`2023-01-31T01:59:06.520844695+00:00 FATAL HomeSeer Z-Wave Switches  Lua: runtime error: [string "init.lua"]:119: [string "homeseer-switches/init.lua"]:24: **Module 'st.Device' not found**
stack traceback:
        [C]: in function 'error'
        [string "env builder"]:95: in global 'require'
        [string "init.lua"]:119: in main chunk`
        
I took the opportunity to correct the error, and push a variety of incremental changes from my beta branch to the production channel.  Unfortunately, it appears that the maximum interval for this to propagate could be up to 12 hours.

https://community.smartthings.com/t/force-edge-driver-update-without-cli/246544/4

Here is the specific command line if you want to try to "force" an update per the above community post:

`smartthings edge:drivers:install -C c408fa0b-438f-4d00-bf36-efe7343c66b7 5f2d5dca-fcd9-4895-805a-6e976dd349d1`

**Comment by RandomEngy** [comment]
Thanks, everything is working again.
